services:
  caddy:
    image: caddy:2.10.2
    container_name: caddy
    restart: always
    stdin_open: true
    tty: true
    volumes:
      - /srv/selfhosted/caddy/data:/data
      - /srv/selfhosted/caddy/config:/config
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 80:80
      - 443:443
    entrypoint: /usr/bin/caddy run --adapter caddyfile --config /config/Caddyfile
    networks:
      - reverseproxy-nw
    labels:
      wud.watch: true
      wud.tag.include: '^\d+\.\d+\.\d+$$'
      wud.link.template: 'https://github.com/caddyserver/caddy/releases/tag/$${major}.$${minor}.$${patch}'

networks:
  reverseproxy-nw:
    external: true