services:
  caddy:
    image: caddy:2.10.2
    container_name: caddy
    restart: always
    stdin_open: true
    tty: true
    volumes:
      - /srv/selfhosted/caddy/data:/data
      - /srv/selfhosted/caddy/config:/config
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 80:80
      - 443:443
    entrypoint: /usr/bin/caddy run --adapter caddyfile --config /config/Caddyfile
    env_file:
      - env/caddy.env
    networks:
      - reverseproxy-nw

networks:
  reverseproxy-nw:
    external: true