services:
  headscale:
    container_name: headscale
    image: headscale/headscale:0.23.0
    restart: unless-stopped
    volumes:
      - /srv/selfhosted/headscale/config:/etc/headscale
      - /srv/selfhosted/headscale/data:/var/lib/headscale
    entrypoint: headscale serve
    env_file:
      - /srv/selfhosted/headscale/env/headscale.env
    networks:
      - reverseproxy-nw

  headscale-ui:
    container_name: headscale-ui
    image: ghcr.io/gurucomputing/headscale-ui:latest
    restart: unless-stopped
    networks:
      - reverseproxy-nw
     
networks:
  reverseproxy-nw:
    external: true