services:
  headscale:
    container_name: headscale
    image: headscale/headscale:0.27.1
    env_file:
      - .env
    restart: unless-stopped
    volumes:
      - /srv/selfhosted/headscale/config:/etc/headscale
      - /srv/selfhosted/headscale/data:/var/lib/headscale
    entrypoint: headscale serve
    networks:
      - reverseproxy-nw
    labels:
      wud.watch: true
      wud.tag.include: '^\d+\.\d+\.\d+$$'
      wud.link.template: 'https://github.com/juanfont/headscale/releases/tag/$${major}.$${minor}.$${patch}'

  headscale-ui:
    image: ghcr.io/gurucomputing/headscale-ui:latest
    container_name: headscale-ui
    env_file:
      - .env    
    restart: unless-stopped
    networks:
      - reverseproxy-nw
    labels:
      wud.watch: true
      wud.tag.include: latest
      wud.tag.digest: true

networks:
  reverseproxy-nw:
    external: true