services:
  portainer:
    container_name: portainer
    image: portainer/portainer-ce:2.33.6
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer-data:/data
    #ports:
      #- 127.0.0.1:9443:9443
      #- 127.0.0.1:8000:8000  # Remove if you do not intend to use Edge Agents
    networks:
      - reverseproxy-nw

volumes:
  portainer-data:
    name: portainer-data

networks:
  reverseproxy-nw:
    external: true