services:
  portainer:
    container_name: portainer
    image: portainer/portainer-ce:2.37.0
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer-data:/data
    #ports:
      #- 127.0.0.1:9443:9443
      #- 127.0.0.1:8000:8000  # Remove if you do not intend to use Edge Agents
    networks:
      - reverseproxy-nw
    labels:
      wud.watch: true
      wud.tag.include: '^\d+\.\d+\.\d+$$'
      wud.link.template: 'https://github.com/portainer/portainer/releases/tag/$${major}.$${minor}.$${patch}'

volumes:
  portainer-data:
    name: portainer-data

networks:
  reverseproxy-nw:
    external: true